# Generated by Django 4.0.2 on 2022-02-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/user')),
                ('cv', models.FileField(upload_to='media/user/Files')),
                ('description', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=200)),
                ('user_profession', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('shadow', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fontawesomeIcone', models.CharField(max_length=500)),
                ('links', models.CharField(max_length=90000000)),
            ],
        ),
        migrations.CreateModel(
            name='Workingjourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Projects_completed', models.IntegerField(max_length=10)),
                ('Cup_of_coffee', models.IntegerField(max_length=10)),
                ('Satisfied_clients', models.IntegerField(max_length=10)),
                ('ProjectsCompleted', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/user/Services')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.servicescolor')),
            ],
        ),
    ]
