# Generated by Django 4.0.2 on 2022-02-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingjourney',
            name='Cup_of_coffee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workingjourney',
            name='ProjectsCompleted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workingjourney',
            name='Projects_completed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workingjourney',
            name='Satisfied_clients',
            field=models.IntegerField(),
        ),
    ]
