# Generated by Django 4.0.2 on 2022-02-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_username_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='data_color',
            field=models.CharField(default='FFD15C', max_length=50),
        ),
    ]
