# Generated by Django 4.0.2 on 2022-02-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_resent_work_popup_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resent_work',
            name='popup_img',
            field=models.FileField(upload_to='media/work/popup_thumbnail'),
        ),
        migrations.AlterField(
            model_name='resent_work',
            name='thumbnail_img',
            field=models.FileField(upload_to='media/work/thumbnail'),
        ),
    ]
