# Generated by Django 4.0.2 on 2022-02-11 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_resent_work_popup_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resent_work_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='resent_work',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.resent_work_category'),
        ),
    ]
